### PR TITLE
New common facts, small changes in the role

### PR DESCRIPTION
**Pull request by drybjed**

### CODE REVIEW

**Comment by ypid** [comment]
When passing data from Jinja to Python, you should decode the JSON object in Python and not rely on the normal Python syntax being a superset of JSON. Refs: `admin_blacklist_users`, `output`

**Comment by ypid** [comment]
@drybjed Should all DebOps role now prefer `ansible_local.core.fqdn` and fall back to `ansible_fqdn`? What is the advantage to do that?

**Comment by drybjed** [comment]
If/When more roles switch to using this variable instead of `ansible_fqdn` directly by default, it will be eaiser to host services on a different domain than the infrastructure itself.

I haven't really planned to switch all roles to it right away, I've added these variables because they are very common in the roles. Right now if you want to use a different domain than your host domain you would need to set that for each role individually in the inventory. These variables should make this easier (of course you still can set each role individually), just like with other common facts provided by `debops.core`.

**Comment by ypid** [comment]
OK. I don’t have a use case for this myself (yet). I usually just bootstrap a host in another domain when I use that mainly to host servers but preferring `ansible_local.core.*` allows more flexibility so I am in :wink:

**Pull request merged**
